// automatically generated by the FlatBuffers compiler, do not modify

package no.kartverket.nibas.flatbuffer.MatrikkelDB.Kode;

@SuppressWarnings("unused")
public final class GrensemerkeKode {
  private GrensemerkeKode() { }
  public static final byte RIKSGRENSEMERKE = 0;
  public static final byte RIKSGRENSEROYS = 1;
  public static final byte RIKSGRENSE_ANNET = 2;
  public static final byte OFFENTLIG_GODKJENT_GRENSEMERKE = 3;
  public static final byte BOLT = 4;
  public static final byte KORS = 5;
  public static final byte ROR = 6;
  public static final byte GRENSESTEIN = 7;
  public static final byte BOREHULL = 8;
  public static final byte GRENSEPALE = 9;
  public static final byte KAMJERN = 10;
  public static final byte ANNET = 11;
  public static final byte GRENSETRE = 12;
  public static final byte STEINGJERDE = 13;
  public static final byte STEIN_MED_KORS_OG_VITNER = 14;
  public static final byte GJERDESTOLPE = 15;
  public static final byte ANNEN_DETALJ = 16;
  public static final byte MIDTI_VEG = 17;
  public static final byte VEG_KANT = 18;
  public static final byte MIDTI_BEKK_ELV = 19;
  public static final byte DJUPALEN = 20;
  public static final byte MURHJORNE = 21;
  public static final byte HUSHJORNE = 22;
  public static final byte UMERKET = 23;
  public static final byte UKJENT = 25;
  public static final byte ASFALTSPIKER = 26;
  public static final byte RETNINGSPUNKT = 27;
  public static final byte GEOMETRISK_HJELPEPUNKT = 28;
  public static final byte KRONROYS = 29;
  public static final byte HOIFJELDSKOMMISJONENS_ROYS = 30;
  public static final byte HOIFJELDSKOMMISJONENS_BOLT = 31;
  public static final byte BYSTEIN = 32;
  public static final byte STEINBLOKK = 33;
  public static final byte FASTMERKE = 34;

  public static final String[] names = { "RIKSGRENSEMERKE", "RIKSGRENSEROYS", "RIKSGRENSE_ANNET", "OFFENTLIG_GODKJENT_GRENSEMERKE", "BOLT", "KORS", "ROR", "GRENSESTEIN", "BOREHULL", "GRENSEPALE", "KAMJERN", "ANNET", "GRENSETRE", "STEINGJERDE", "STEIN_MED_KORS_OG_VITNER", "GJERDESTOLPE", "ANNEN_DETALJ", "MIDTI_VEG", "VEG_KANT", "MIDTI_BEKK_ELV", "DJUPALEN", "MURHJORNE", "HUSHJORNE", "UMERKET", "", "UKJENT", "ASFALTSPIKER", "RETNINGSPUNKT", "GEOMETRISK_HJELPEPUNKT", "KRONROYS", "HOIFJELDSKOMMISJONENS_ROYS", "HOIFJELDSKOMMISJONENS_BOLT", "BYSTEIN", "STEINBLOKK", "FASTMERKE", };

  public static String name(int e) { return names[e]; }
}

