server:
  port: 8080

nibas:
  api:
    base-url: ${nibas.backend.host}/v1/
  arbeidsliste:
    api-key: ${nibas.arbeidsliste.api-key}


# API-key mot nibas-backend
api:
  key:
    matrikkel: ${api.key.matrikkel}

spring:
  main:
    banner-mode: "OFF"
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        default_schema: nibas_arbeidsliste_schema
    show-sql: true
  flyway:
    clean-disabled: false
    validate-on-migrate: false
  data:
    initialization:
      enabled: true

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: 'health, prometheus'
    jmx:
      exposure:
        include: '*'
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      access: unrestricted
  info:
    env:
      enabled: true

info:
  application:
    name: 'nibas-arbeidsliste'
    version: ${PROJECT_VERSION:0.0.1}
