logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        default_schema: nibas_arbeidsliste_schema
    show-sql: false
    open-in-view: false
  sql:
    init:
      mode: never
      platform: postgresql

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    docExpansion: none
  packages-to-scan: no.kartverket.nibas.nibasarbeidsliste.controller

matrikkelen:
  urlEndringslogg: https://matrikkel.no/matrikkelapi/wsapi/v1
  username: ${MATRIKKELEN_USERNAME}
  password: ${MATRIKKELEN_PASSWORD}
  sync-on-startup: false
  patch-on-startup: false
