// automatically generated by the FlatBuffers compiler, do not modify

package no.kartverket.nibas.flatbuffer.Nibas.Common;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Matrikkelnummer extends Struct {
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Matrikkelnummer __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public short kommunenummer() { return bb.getShort(bb_pos + 0); }
  public int gaardsnummer() { return bb.getInt(bb_pos + 4); }
  public short bruksnummer() { return bb.getShort(bb_pos + 8); }
  public short festenummer() { return bb.getShort(bb_pos + 10); }
  public short seksjonsnummer() { return bb.getShort(bb_pos + 12); }

  public static int createMatrikkelnummer(FlatBufferBuilder builder, short kommunenummer, int gaardsnummer, short bruksnummer, short festenummer, short seksjonsnummer) {
    builder.prep(4, 16);
    builder.pad(2);
    builder.putShort(seksjonsnummer);
    builder.putShort(festenummer);
    builder.putShort(bruksnummer);
    builder.putInt(gaardsnummer);
    builder.pad(2);
    builder.putShort(kommunenummer);
    return builder.offset();
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Matrikkelnummer get(int j) { return get(new Matrikkelnummer(), j); }
    public Matrikkelnummer get(Matrikkelnummer obj, int j) {  return obj.__assign(__element(j), bb); }
  }
}

