# nonk8s
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "nibas-arbeidsliste"
  tags:
  - "internal"
spec:
  type: "service"
  lifecycle: "production"
  owner: "smia"
  system: "nibas"
  providesApis:
  - "nibas-arbeidsliste-api"
---
apiVersion: "backstage.io/v1alpha1"
kind: "API"
metadata:
  name: "nibas-arbeidsliste-api"
  tags:
  - "internal"
spec:
  type: "openapi"
  lifecycle: "production"
  owner: "smia"
  system: "nibas"
  definition: |
    openapi: "3.0.0"
    info:
        title: nibas-arbeidsliste API
    paths:
