// automatically generated by the FlatBuffers compiler, do not modify

package no.kartverket.nibas.flatbuffer.Nibas;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Koordinat extends Struct {
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Koordinat __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int x() { return bb.getInt(bb_pos + 0); }
  public int y() { return bb.getInt(bb_pos + 4); }

  public static int createKoordinat(FlatBufferBuilder builder, int x, int y) {
    builder.prep(4, 8);
    builder.putInt(y);
    builder.putInt(x);
    return builder.offset();
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Koordinat get(int j) { return get(new Koordinat(), j); }
    public Koordinat get(Koordinat obj, int j) {  return obj.__assign(__element(j), bb); }
  }
}

