// automatically generated by the FlatBuffers compiler, do not modify

package no.kartverket.nibas.flatbuffer.Nibas;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class MatrikkelGrense extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static MatrikkelGrense getRootAsMatrikkelGrense(ByteBuffer _bb) { return getRootAsMatrikkelGrense(_bb, new MatrikkelGrense()); }
  public static MatrikkelGrense getRootAsMatrikkelGrense(ByteBuffer _bb, MatrikkelGrense obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public MatrikkelGrense __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public no.kartverket.nibas.flatbuffer.Nibas.Koordinat coordinates(int j) { return coordinates(new no.kartverket.nibas.flatbuffer.Nibas.Koordinat(), j); }
  public no.kartverket.nibas.flatbuffer.Nibas.Koordinat coordinates(no.kartverket.nibas.flatbuffer.Nibas.Koordinat obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o) + j * 8, bb) : null; }
  public int coordinatesLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public no.kartverket.nibas.flatbuffer.Nibas.Koordinat.Vector coordinatesVector() { return coordinatesVector(new no.kartverket.nibas.flatbuffer.Nibas.Koordinat.Vector()); }
  public no.kartverket.nibas.flatbuffer.Nibas.Koordinat.Vector coordinatesVector(no.kartverket.nibas.flatbuffer.Nibas.Koordinat.Vector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), 8, bb) : null; }
  public byte hjelpelinjeKode() { int o = __offset(6); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public boolean omtvistet() { int o = __offset(8); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public byte terrengdetaljKode() { int o = __offset(10); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public byte administrativGrenseKode() { int o = __offset(12); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public byte maalemetodeKode() { int o = __offset(14); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public int maalingsnoyaktighet() { int o = __offset(16); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public no.kartverket.nibas.flatbuffer.Nibas.Common.LocalDate datafangstdato() { return datafangstdato(new no.kartverket.nibas.flatbuffer.Nibas.Common.LocalDate()); }
  public no.kartverket.nibas.flatbuffer.Nibas.Common.LocalDate datafangstdato(no.kartverket.nibas.flatbuffer.Nibas.Common.LocalDate obj) { int o = __offset(18); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }
  public byte noyaktighetsklasse() { int o = __offset(20); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public no.kartverket.nibas.flatbuffer.Nibas.Common.Timestamp oppdateringsdato() { return oppdateringsdato(new no.kartverket.nibas.flatbuffer.Nibas.Common.Timestamp()); }
  public no.kartverket.nibas.flatbuffer.Nibas.Common.Timestamp oppdateringsdato(no.kartverket.nibas.flatbuffer.Nibas.Common.Timestamp obj) { int o = __offset(22); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }
  public String kommunenrstrengcache() { int o = __offset(24); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer kommunenrstrengcacheAsByteBuffer() { return __vector_as_bytebuffer(24, 1); }
  public ByteBuffer kommunenrstrengcacheInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 24, 1); }

  public static void startMatrikkelGrense(FlatBufferBuilder builder) { builder.startTable(11); }
  public static void addCoordinates(FlatBufferBuilder builder, int coordinatesOffset) { builder.addOffset(0, coordinatesOffset, 0); }
  public static void startCoordinatesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(8, numElems, 4); }
  public static void addHjelpelinjeKode(FlatBufferBuilder builder, byte hjelpelinjeKode) { builder.addByte(1, hjelpelinjeKode, 0); }
  public static void addOmtvistet(FlatBufferBuilder builder, boolean omtvistet) { builder.addBoolean(2, omtvistet, false); }
  public static void addTerrengdetaljKode(FlatBufferBuilder builder, byte terrengdetaljKode) { builder.addByte(3, terrengdetaljKode, 0); }
  public static void addAdministrativGrenseKode(FlatBufferBuilder builder, byte administrativGrenseKode) { builder.addByte(4, administrativGrenseKode, 0); }
  public static void addMaalemetodeKode(FlatBufferBuilder builder, byte maalemetodeKode) { builder.addByte(5, maalemetodeKode, 0); }
  public static void addMaalingsnoyaktighet(FlatBufferBuilder builder, int maalingsnoyaktighet) { builder.addInt(6, maalingsnoyaktighet, 0); }
  public static void addDatafangstdato(FlatBufferBuilder builder, int datafangstdatoOffset) { builder.addStruct(7, datafangstdatoOffset, 0); }
  public static void addNoyaktighetsklasse(FlatBufferBuilder builder, byte noyaktighetsklasse) { builder.addByte(8, noyaktighetsklasse, 0); }
  public static void addOppdateringsdato(FlatBufferBuilder builder, int oppdateringsdatoOffset) { builder.addStruct(9, oppdateringsdatoOffset, 0); }
  public static void addKommunenrstrengcache(FlatBufferBuilder builder, int kommunenrstrengcacheOffset) { builder.addOffset(10, kommunenrstrengcacheOffset, 0); }
  public static int endMatrikkelGrense(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 4);  // coordinates
    builder.required(o, 22);  // oppdateringsdato
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public MatrikkelGrense get(int j) { return get(new MatrikkelGrense(), j); }
    public MatrikkelGrense get(MatrikkelGrense obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

