// automatically generated by the FlatBuffers compiler, do not modify

package no.kartverket.nibas.flatbuffer.Nibas;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class MatrikkelGrenseDB extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static MatrikkelGrenseDB getRootAsMatrikkelGrenseDB(ByteBuffer _bb) { return getRootAsMatrikkelGrenseDB(_bb, new MatrikkelGrenseDB()); }
  public static MatrikkelGrenseDB getRootAsMatrikkelGrenseDB(ByteBuffer _bb, MatrikkelGrenseDB obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public MatrikkelGrenseDB __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public no.kartverket.nibas.flatbuffer.Nibas.MatrikkelGrenseEntry matrikkelgrenser(int j) { return matrikkelgrenser(new no.kartverket.nibas.flatbuffer.Nibas.MatrikkelGrenseEntry(), j); }
  public no.kartverket.nibas.flatbuffer.Nibas.MatrikkelGrenseEntry matrikkelgrenser(no.kartverket.nibas.flatbuffer.Nibas.MatrikkelGrenseEntry obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int matrikkelgrenserLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public no.kartverket.nibas.flatbuffer.Nibas.MatrikkelGrenseEntry matrikkelgrenserByKey(long key) { int o = __offset(4); return o != 0 ? no.kartverket.nibas.flatbuffer.Nibas.MatrikkelGrenseEntry.__lookup_by_key(null, __vector(o), key, bb) : null; }
  public no.kartverket.nibas.flatbuffer.Nibas.MatrikkelGrenseEntry matrikkelgrenserByKey(no.kartverket.nibas.flatbuffer.Nibas.MatrikkelGrenseEntry obj, long key) { int o = __offset(4); return o != 0 ? no.kartverket.nibas.flatbuffer.Nibas.MatrikkelGrenseEntry.__lookup_by_key(obj, __vector(o), key, bb) : null; }
  public no.kartverket.nibas.flatbuffer.Nibas.MatrikkelGrenseEntry.Vector matrikkelgrenserVector() { return matrikkelgrenserVector(new no.kartverket.nibas.flatbuffer.Nibas.MatrikkelGrenseEntry.Vector()); }
  public no.kartverket.nibas.flatbuffer.Nibas.MatrikkelGrenseEntry.Vector matrikkelgrenserVector(no.kartverket.nibas.flatbuffer.Nibas.MatrikkelGrenseEntry.Vector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public long firstKey() { int o = __offset(6); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public long lastKey() { int o = __offset(8); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }

  public static int createMatrikkelGrenseDB(FlatBufferBuilder builder,
      int matrikkelgrenserOffset,
      long firstKey,
      long lastKey) {
    builder.startTable(3);
    MatrikkelGrenseDB.addLastKey(builder, lastKey);
    MatrikkelGrenseDB.addFirstKey(builder, firstKey);
    MatrikkelGrenseDB.addMatrikkelgrenser(builder, matrikkelgrenserOffset);
    return MatrikkelGrenseDB.endMatrikkelGrenseDB(builder);
  }

  public static void startMatrikkelGrenseDB(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addMatrikkelgrenser(FlatBufferBuilder builder, int matrikkelgrenserOffset) { builder.addOffset(0, matrikkelgrenserOffset, 0); }
  public static int createMatrikkelgrenserVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startMatrikkelgrenserVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addFirstKey(FlatBufferBuilder builder, long firstKey) { builder.addLong(1, firstKey, 0L); }
  public static void addLastKey(FlatBufferBuilder builder, long lastKey) { builder.addLong(2, lastKey, 0L); }
  public static int endMatrikkelGrenseDB(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 4);  // matrikkelgrenser
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public MatrikkelGrenseDB get(int j) { return get(new MatrikkelGrenseDB(), j); }
    public MatrikkelGrenseDB get(MatrikkelGrenseDB obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

