// automatically generated by the FlatBuffers compiler, do not modify

package no.kartverket.nibas.flatbuffer.Nibas;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Teig extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static Teig getRootAsTeig(ByteBuffer _bb) { return getRootAsTeig(_bb, new Teig()); }
  public static Teig getRootAsTeig(ByteBuffer _bb, Teig obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Teig __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public no.kartverket.nibas.flatbuffer.Nibas.Common.Matrikkelnummer matrikkelnummer(int j) { return matrikkelnummer(new no.kartverket.nibas.flatbuffer.Nibas.Common.Matrikkelnummer(), j); }
  public no.kartverket.nibas.flatbuffer.Nibas.Common.Matrikkelnummer matrikkelnummer(no.kartverket.nibas.flatbuffer.Nibas.Common.Matrikkelnummer obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o) + j * 16, bb) : null; }
  public int matrikkelnummerLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public no.kartverket.nibas.flatbuffer.Nibas.Common.Matrikkelnummer.Vector matrikkelnummerVector() { return matrikkelnummerVector(new no.kartverket.nibas.flatbuffer.Nibas.Common.Matrikkelnummer.Vector()); }
  public no.kartverket.nibas.flatbuffer.Nibas.Common.Matrikkelnummer.Vector matrikkelnummerVector(no.kartverket.nibas.flatbuffer.Nibas.Common.Matrikkelnummer.Vector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), 16, bb) : null; }
  public no.kartverket.nibas.flatbuffer.Nibas.LinearRing shell() { return shell(new no.kartverket.nibas.flatbuffer.Nibas.LinearRing()); }
  public no.kartverket.nibas.flatbuffer.Nibas.LinearRing shell(no.kartverket.nibas.flatbuffer.Nibas.LinearRing obj) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public no.kartverket.nibas.flatbuffer.Nibas.LinearRing holes(int j) { return holes(new no.kartverket.nibas.flatbuffer.Nibas.LinearRing(), j); }
  public no.kartverket.nibas.flatbuffer.Nibas.LinearRing holes(no.kartverket.nibas.flatbuffer.Nibas.LinearRing obj, int j) { int o = __offset(8); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int holesLength() { int o = __offset(8); return o != 0 ? __vector_len(o) : 0; }
  public no.kartverket.nibas.flatbuffer.Nibas.LinearRing.Vector holesVector() { return holesVector(new no.kartverket.nibas.flatbuffer.Nibas.LinearRing.Vector()); }
  public no.kartverket.nibas.flatbuffer.Nibas.LinearRing.Vector holesVector(no.kartverket.nibas.flatbuffer.Nibas.LinearRing.Vector obj) { int o = __offset(8); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createTeig(FlatBufferBuilder builder,
      int matrikkelnummerOffset,
      int shellOffset,
      int holesOffset) {
    builder.startTable(3);
    Teig.addHoles(builder, holesOffset);
    Teig.addShell(builder, shellOffset);
    Teig.addMatrikkelnummer(builder, matrikkelnummerOffset);
    return Teig.endTeig(builder);
  }

  public static void startTeig(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addMatrikkelnummer(FlatBufferBuilder builder, int matrikkelnummerOffset) { builder.addOffset(0, matrikkelnummerOffset, 0); }
  public static void startMatrikkelnummerVector(FlatBufferBuilder builder, int numElems) { builder.startVector(16, numElems, 4); }
  public static void addShell(FlatBufferBuilder builder, int shellOffset) { builder.addOffset(1, shellOffset, 0); }
  public static void addHoles(FlatBufferBuilder builder, int holesOffset) { builder.addOffset(2, holesOffset, 0); }
  public static int createHolesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startHolesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endTeig(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 4);  // matrikkelnummer
    builder.required(o, 6);  // shell
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Teig get(int j) { return get(new Teig(), j); }
    public Teig get(Teig obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

