server:
  port: 8082

management:
  server:
    port: 8083

nibas:
  api:
    base-url: http://localhost:8080/v1
  arbeidsliste:
    api-key: 'super-secret-api-key'


spring:
  datasource:
    # Bruker NIBAS-database med eget schema og bruker.
    # Bruker sin default search_path for å bruke riktig schema.
    url: jdbc:postgresql://localhost:5432/nibas
    username: nibas_arbeidsliste
    password: nibas_arbeidsliste
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        default_schema: nibas_arbeidsliste_schema
    show-sql: true
  flyway:
    clean-disabled: false
    validate-on-migrate: false
  data:
    initialization:
      enabled: true

logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'
