// automatically generated by the FlatBuffers compiler, do not modify

package no.kartverket.nibas.flatbuffer.Nibas.Common;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class LocalDate extends Struct {
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public LocalDate __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int year() { return bb.getInt(bb_pos + 0); }
  public short month() { return bb.getShort(bb_pos + 4); }
  public short day() { return bb.getShort(bb_pos + 6); }

  public static int createLocalDate(FlatBufferBuilder builder, int year, short month, short day) {
    builder.prep(4, 8);
    builder.putShort(day);
    builder.putShort(month);
    builder.putInt(year);
    return builder.offset();
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public LocalDate get(int j) { return get(new LocalDate(), j); }
    public LocalDate get(LocalDate obj, int j) {  return obj.__assign(__element(j), bb); }
  }
}

