[versions]
kotlin = "2.3.0"
springBoot = "4.0.1"
springDependencyManagement = "1.1.7"
graalvmNative = "0.11.4"
logstashLogback = "9.0"
springdocOpenapi = "3.0.1"
micrometerPrometheus = "1.16.2"
flyway = "11.20.1"
jts-core = "1.20.0"
jackson-datatype-jts = "2.0.0"
postgis-jdbc = "2025.1.1"

[libraries]
# Spring Boot
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-boot-starter-webflux = { module = "org.springframework.boot:spring-boot-starter-webflux" }
spring-boot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa" }
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
spring-boot-starter-security = { module = "org.springframework.boot:spring-boot-starter-security" }
spring-boot-devtools = { module = "org.springframework.boot:spring-boot-devtools" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }

# Database
postgresql = { module = "org.postgresql:postgresql" }
hibernate-spatial = { module = "org.hibernate.orm:hibernate-spatial" }

# Kotlin
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect" }
kotlin-test-junit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5" }

# Jackson
jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin" }
jackson-datatype-jts = { module = "org.n52.jackson:jackson-datatype-jts", version.ref = "jackson-datatype-jts" }

locationtech-jts-core = { module = "org.locationtech.jts:jts-core", version.ref = "jts-core" }
postgis-jdbc = { module = "net.postgis:postgis-jdbc", version.ref = "postgis-jdbc" }

# Logging and Monitoring
logstash-logback-encoder = { module = "net.logstash.logback:logstash-logback-encoder", version.ref = "logstashLogback" }
micrometer-prometheus = { module = "io.micrometer:micrometer-registry-prometheus", version.ref = "micrometerPrometheus" }

# OpenAPI
springdoc-openapi-webmvc-api = { module = "org.springdoc:springdoc-openapi-starter-webmvc-api", version.ref = "springdocOpenapi" }
springdoc-openapi-webmvc-ui = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "springdocOpenapi" }

# Testing
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }

# Flyway
flyway-core = { module = "org.flywaydb:flyway-core", version.ref = "flyway" }
flyway-database-postgresql = { module = "org.flywaydb:flyway-database-postgresql", version.ref = "flyway" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "springDependencyManagement" }
graalvm-native = { id = "org.graalvm.buildtools.native", version.ref = "graalvmNative" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
