// automatically generated by the FlatBuffers compiler, do not modify

package no.kartverket.nibas.flatbuffer.MatrikkelDB.Kode;

@SuppressWarnings("unused")
public final class AdministrativGrenseKode {
  private AdministrativGrenseKode() { }
  public static final byte IKKE_ADM_GRENSE = 0;
  public static final byte KOMMUNEGRENSE = 1;
  public static final byte FYLKESGRENSE = 2;
  public static final byte RIKSGRENSE = 3;
  public static final byte TERRITORIALGRENSE = 4;

  public static final String[] names = { "IKKE_ADM_GRENSE", "KOMMUNEGRENSE", "FYLKESGRENSE", "RIKSGRENSE", "TERRITORIALGRENSE", };

  public static String name(int e) { return names[e]; }
}

