// automatically generated by the FlatBuffers compiler, do not modify

package no.kartverket.nibas.flatbuffer.MatrikkelDB.Kode;

@SuppressWarnings("unused")
public final class GrensemerkeNedsattIKode {
  private GrensemerkeNedsattIKode() { }
  public static final byte NEDSATT_I_RIKSGRENSE = 0;
  public static final byte NEDSATT_I_IKKE_SPESIFISERT = 1;
  public static final byte NEDSATT_I_JORD = 2;
  public static final byte NEDSATT_I_FJELL = 3;
  public static final byte NEDSATT_I_JORDFAST_STEIN = 4;
  public static final byte NEDSATT_I_ANNEN_TERRENGDETALJ = 5;
  public static final byte NEDSATT_I_MUR = 8;
  public static final byte NEDSATT_I_STEINGJERDE = 9;
  public static final byte NEDSATT_I_VANN = 10;

  public static final String[] names = { "NEDSATT_I_RIKSGRENSE", "NEDSATT_I_IKKE_SPESIFISERT", "NEDSATT_I_JORD", "NEDSATT_I_FJELL", "NEDSATT_I_JORDFAST_STEIN", "NEDSATT_I_ANNEN_TERRENGDETALJ", "", "", "NEDSATT_I_MUR", "NEDSATT_I_STEINGJERDE", "NEDSATT_I_VANN", };

  public static String name(int e) { return names[e]; }
}

