// automatically generated by the FlatBuffers compiler, do not modify

package no.kartverket.nibas.flatbuffer.MatrikkelDB.Kode;

@SuppressWarnings("unused")
public final class HjelpelineKode {
  private HjelpelineKode() { }
  public static final byte IKKE_HJELPELINJE = 0;
  public static final byte VANNKANT = 1;
  public static final byte VEGKANT = 2;
  public static final byte FIKTIV_GRENSE = 3;
  public static final byte PUNKTFESTE = 4;
  public static final byte TEIGDELER = 5;

  public static final String[] names = { "IKKE_HJELPELINJE", "VANNKANT", "VEGKANT", "FIKTIV_GRENSE", "PUNKTFESTE", "TEIGDELER", };

  public static String name(int e) { return names[e]; }
}

