// automatically generated by the FlatBuffers compiler, do not modify

package no.kartverket.nibas.flatbuffer.MatrikkelDB.Kode;

@SuppressWarnings("unused")
public final class KoordinatsystemKode {
  private KoordinatsystemKode() { }
  public static final byte NGO_AKSE_1 = 0;
  public static final byte NGO_AKSE_2 = 1;
  public static final byte NGO_AKSE_3 = 2;
  public static final byte NGO_AKSE_4 = 3;
  public static final byte NGO_AKSE_5 = 4;
  public static final byte NGO_AKSE_6 = 5;
  public static final byte NGO_AKSE_7 = 6;
  public static final byte NGO_AKSE_8 = 7;
  public static final byte NGO_GEO = 8;
  public static final byte EUREF_SONE_31 = 9;
  public static final byte EUREF_SONE_32 = 10;
  public static final byte EUREF_SONE_33 = 11;
  public static final byte EUREF_SONE_34 = 12;
  public static final byte EUREF_SONE_35 = 13;
  public static final byte EUREF_SONE_36 = 14;
  public static final byte ED50_SONE_31 = 15;
  public static final byte ED50_SONE_32 = 16;
  public static final byte ED50_SONE_33 = 17;
  public static final byte ED50_SONE_34 = 18;
  public static final byte ED50_SONE_35 = 19;
  public static final byte ED50_SONE_36 = 20;
  public static final byte ED50_GEO = 21;
  public static final byte MORE_A = 22;
  public static final byte MORE_B = 23;
  public static final byte EUREF_GEO = 24;
  public static final byte NGO56A = 25;
  public static final byte NGO56B = 26;

  public static final String[] names = { "NGO_AKSE_1", "NGO_AKSE_2", "NGO_AKSE_3", "NGO_AKSE_4", "NGO_AKSE_5", "NGO_AKSE_6", "NGO_AKSE_7", "NGO_AKSE_8", "NGO_GEO", "EUREF_SONE_31", "EUREF_SONE_32", "EUREF_SONE_33", "EUREF_SONE_34", "EUREF_SONE_35", "EUREF_SONE_36", "ED50_SONE_31", "ED50_SONE_32", "ED50_SONE_33", "ED50_SONE_34", "ED50_SONE_35", "ED50_SONE_36", "ED50_GEO", "MORE_A", "MORE_B", "EUREF_GEO", "NGO56A", "NGO56B", };

  public static String name(int e) { return names[e]; }
}

