// automatically generated by the FlatBuffers compiler, do not modify

package no.kartverket.nibas.flatbuffer.MatrikkelDB.Kode;

@SuppressWarnings("unused")
public final class NoyaktighetsklasseKode {
  private NoyaktighetsklasseKode() { }
  public static final byte MALE_NOYAKTIGHET_EUREF = 0;
  public static final byte MALE_NOYAKTIGHET_NGO = 1;
  public static final byte TEKNISK_KART_NOYAKTIGHET = 2;
  public static final byte OKONOMISK_KART_NOYAKTIGHET = 3;
  public static final byte SKISSE_NOYAKTIGHET = 4;
  public static final byte NORGE1_50000 = 5;
  public static final byte INGEN_NOYAKTIGHET = 6;

  public static final String[] names = { "MALE_NOYAKTIGHET_EUREF", "MALE_NOYAKTIGHET_NGO", "TEKNISK_KART_NOYAKTIGHET", "OKONOMISK_KART_NOYAKTIGHET", "SKISSE_NOYAKTIGHET", "NORGE1_50000", "INGEN_NOYAKTIGHET", };

  public static String name(int e) { return names[e]; }
}

