// automatically generated by the FlatBuffers compiler, do not modify

package no.kartverket.nibas.flatbuffer.MatrikkelDB.Kode;

@SuppressWarnings("unused")
public final class TerrengdetaljKode {
  private TerrengdetaljKode() { }
  public static final byte IKKE_TERRENG_DETALJ = 0;
  public static final byte ANNET_GJERDE = 1;
  public static final byte ANNET = 2;
  public static final byte ELVEBEKKE_DYPAAL = 3;
  public static final byte BYGNING = 4;
  public static final byte BYGNINGS_ANLEGG = 5;
  public static final byte ELVE_BEKKE_KANT = 6;
  public static final byte ELVE_BEKKE_MIDT = 7;
  public static final byte GENERALISERT_GEOMETRISK_MIDTLINJE = 8;
  public static final byte HAVKONTUR = 9;
  public static final byte INNSJO_KANT = 10;
  public static final byte LAV_BREKK = 11;
  public static final byte STI_KJERREVEG = 12;
  public static final byte STEIN_GJERDE = 13;
  public static final byte VEG_KANT = 14;
  public static final byte VEG_MIDT = 15;
  public static final byte VANNSKILLE = 16;

  public static final String[] names = { "IKKE_TERRENG_DETALJ", "ANNET_GJERDE", "ANNET", "ELVEBEKKE_DYPAAL", "BYGNING", "BYGNINGS_ANLEGG", "ELVE_BEKKE_KANT", "ELVE_BEKKE_MIDT", "GENERALISERT_GEOMETRISK_MIDTLINJE", "HAVKONTUR", "INNSJO_KANT", "LAV_BREKK", "STI_KJERREVEG", "STEIN_GJERDE", "VEG_KANT", "VEG_MIDT", "VANNSKILLE", };

  public static String name(int e) { return names[e]; }
}

