namespace MatrikkelDB.Kode;

enum HjelpelineKode : int8 {
  IKKE_HJELPELINJE = 0,
  VANNKANT = 1,
  VEGKANT = 2,
  FIKTIV_GRENSE = 3,
  PUNKTFESTE = 4,
  TEIGDELER = 5,
}

enum TerrengdetaljKode : int8 {
  IKKE_TERRENG_DETALJ = 0,
  ANNET_GJERDE = 1,
  ANNET = 2,
  ELVEBEKKE_DYPAAL = 3,
  BYGNING = 4,
  BYGNINGS_ANLEGG = 5,
  ELVE_BEKKE_KANT = 6,
  ELVE_BEKKE_MIDT = 7,
  GENERALISERT_GEOMETRISK_MIDTLINJE = 8,
  HAVKONTUR = 9,
  INNSJO_KANT = 10,
  LAV_BREKK = 11,
  STI_KJERREVEG = 12,
  STEIN_GJERDE = 13,
  VEG_KANT = 14,
  VEG_MIDT = 15,
  VANNSKILLE = 16,
}

enum AdministrativGrenseKode : int8 {
  IKKE_ADM_GRENSE = 0,
  KOMMUNEGRENSE = 1,
  FYLKESGRENSE = 2,
  RIKSGRENSE = 3,
  TERRITORIALGRENSE = 4,
}

enum MaalemetodeKode : int8 {
  TERRENGMALT = 0,
  TERRENGMALT_TOTALSTASJON = 1,
  TERRENGMALT_TEODOLITT_ELEKTRONISK = 2,
  TERRENGMALT_TEODOLITT_MALEBAND = 3,
  TERRENGMALT_ORTOGONAL = 4,
  UTMAL = 5,
  TATT_FRA_PLAN = 6,
  TERRENGMALT_ANNET = 7,
  STEREOINSTRUMENT = 8,
  STEREOINSTRUMENT_AEROTRIANGULERT = 9,
  STEREOINSTRUMENT_ANALYTISK_PLOTTER = 10,
  STEREOINSTRUMENT_AUTOGRAF = 11,
  DIGITALT_STEREOINSTRUMENT = 12,
  SCANNET = 13,
  SCANNET_BLYANTORIGINAL = 14,
  SCANNET_RISSFOLIE = 15,
  SCANNET_TRANPARENT_GOD = 16,
  SCANNET_TRANPARENT_MINDRE_GOD = 17,
  SCANNET_PAPIRKOPI = 18,
  FLYBAREN_LASERSCANNER = 19,
  DIGITALISERT_ORTOFOTO_FLYBILDE = 20,
  DIGITALISERT_ORTOFOTO_FILM = 21,
  DIGITALISERT_ORTOFOTO_FOTOKOPI = 22,
  DIGITALISERT_FLYBILDE_MONO_FILM = 23,
  DIGITALISERT_FLYBILDE_MONO_FOTOKOPI = 24,
  DIGITALISERT_ORTOFOTO = 25,
  DIGITALISERT_SKJERM_FRA_SATELITT = 26,
  DIGITALISERT_STREK_KART = 27,
  DIGITALISERT_STREK_KART_BLYANTORIG = 28,
  DIGITALISERT_STREK_KART_RISSFOLIE = 29,
  DIGITALISERT_TRANSPARENT_GOD = 30,
  DIGITALISERT_TRANSPARENT_MINDRE_GOD = 31,
  DIGITALISERT_STREK_KART_PAPIKOPI = 32,
  DIGITALISERT_SKJERM_SCANNET = 33,
  GENERERTE_DATA = 34,
  GENERERTE_DATA_TERRENGMODELL = 35,
  GENERERTE_DATA_VEKTET_MIDDEL = 36,
  GENERERT_SIRKELGEOMETRI = 37,
  GENERERTE_DATA_GENERALISERING = 38,
  GENERERT_SENTRALPUNKT = 39,
  SAMMENKNYTNINGSPUNKT = 40,
  KOORDINAL_HENTET_FRA_GAB = 41,
  KOORDINAT_HENTET_FRA_JREG = 42,
  BEREGNET = 43,
  SPESIELLE_METODER = 44,
  SPESIELLE_METODER_STIKKSTANG = 45,
  SPESIELLE_METODER_WATERSTANG = 46,
  SPESIELLE_METODER_MALEHJUL = 47,
  SPESIELLE_METODER_STIGNINGMALER = 48,
  FASTSATT_VED_DOM = 49,
  SPESIELLE_METODER_ANNET = 50,
  FRIHANDSTEGNING = 51,
  FRIHANDSTEGNING_KROKERING = 52,
  FRIHANDSTEGNING_SKJERM = 53,
  TREGHETSSTEDFESTING = 54,
  GPS_KODEMALING_RELATIV = 55,
  GPS_KODEMALING_ENKEL = 56,
  GPS_FASEMALING_STATISK = 57,
  GPS_FASEMALING_ANNET = 58,
  KOMBINASJON_GPS_TREGHET = 59,
  GPS_KINEMATISK = 60,
  UKJENT = 62,
  FASTSATT_PUNKT = 63,
  BILBAREN_LASER = 64,
  LINEAR_REFERANSE = 65,
  DIGITALISERT_PA_SKJERM_FRA_ANDRE_DIGITALE_RASTERDATA = 66,
  DIGITALISERT_PA_SKJERM_FRA_TOLKNING_AV_SEISMIKK = 67,
  VEKTORISERING_AV_LASERDATA = 68,
  GNSS_FASEMALING_FLOAT_LOSNING = 69,
}

enum NoyaktighetsklasseKode : int8 {
  MALE_NOYAKTIGHET_EUREF = 0,
  MALE_NOYAKTIGHET_NGO = 1,
  TEKNISK_KART_NOYAKTIGHET = 2,
  OKONOMISK_KART_NOYAKTIGHET = 3,
  SKISSE_NOYAKTIGHET = 4,
  NORGE1_50000 = 5,
  INGEN_NOYAKTIGHET = 6,
}

enum KoordinatsystemKode : int8 {
  NGO_AKSE_1 = 0,
  NGO_AKSE_2 = 1,
  NGO_AKSE_3 = 2,
  NGO_AKSE_4 = 3,
  NGO_AKSE_5 = 4,
  NGO_AKSE_6 = 5,
  NGO_AKSE_7 = 6,
  NGO_AKSE_8 = 7,
  NGO_GEO = 8,
  EUREF_SONE_31 = 9,
  EUREF_SONE_32 = 10,
  EUREF_SONE_33 = 11,
  EUREF_SONE_34 = 12,
  EUREF_SONE_35 = 13,
  EUREF_SONE_36 = 14,
  ED50_SONE_31 = 15,
  ED50_SONE_32 = 16,
  ED50_SONE_33 = 17,
  ED50_SONE_34 = 18,
  ED50_SONE_35 = 19,
  ED50_SONE_36 = 20,
  ED50_GEO = 21,
  MORE_A = 22,
  MORE_B = 23,
  EUREF_GEO = 24,
  NGO56A = 25,
  NGO56B = 26,
}

enum GrensemerkeKode : int8 {
    RIKSGRENSEMERKE = 0,
    RIKSGRENSEROYS = 1,
    RIKSGRENSE_ANNET = 2,
    OFFENTLIG_GODKJENT_GRENSEMERKE = 3,
    BOLT = 4,
    KORS = 5,
    ROR = 6,
    GRENSESTEIN = 7,
    BOREHULL = 8,
    GRENSEPALE = 9,
    KAMJERN = 10,
    ANNET = 11,
    GRENSETRE = 12,
    STEINGJERDE = 13,
    STEIN_MED_KORS_OG_VITNER = 14,
    GJERDESTOLPE = 15,
    ANNEN_DETALJ = 16,
    MIDTI_VEG = 17,
    VEG_KANT = 18,
    MIDTI_BEKK_ELV = 19,
    DJUPALEN = 20,
    MURHJORNE = 21,
    HUSHJORNE = 22,
    UMERKET = 23,
    UKJENT = 25,
    ASFALTSPIKER = 26,
    RETNINGSPUNKT = 27,
    GEOMETRISK_HJELPEPUNKT = 28,
    KRONROYS = 29,
    HOIFJELDSKOMMISJONENS_ROYS = 30,
    HOIFJELDSKOMMISJONENS_BOLT = 31,
    BYSTEIN = 32,
    STEINBLOKK = 33,
    FASTMERKE = 34,
  }

  enum GrensemerkeNedsattIKode: int8 {
    NEDSATT_I_RIKSGRENSE = 0,
    NEDSATT_I_IKKE_SPESIFISERT = 1,
    NEDSATT_I_JORD = 2,
    NEDSATT_I_FJELL = 3,
    NEDSATT_I_JORDFAST_STEIN = 4,
    NEDSATT_I_ANNEN_TERRENGDETALJ = 5,
    NEDSATT_I_MUR = 8,
    NEDSATT_I_STEINGJERDE = 9,
    NEDSATT_I_VANN = 10,
  }
