// automatically generated by the FlatBuffers compiler, do not modify

package no.kartverket.nibas.flatbuffer.Nibas;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class LinearRing extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_24_3_25(); }
  public static LinearRing getRootAsLinearRing(ByteBuffer _bb) { return getRootAsLinearRing(_bb, new LinearRing()); }
  public static LinearRing getRootAsLinearRing(ByteBuffer _bb, LinearRing obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public LinearRing __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public no.kartverket.nibas.flatbuffer.Nibas.Koordinat coordinates(int j) { return coordinates(new no.kartverket.nibas.flatbuffer.Nibas.Koordinat(), j); }
  public no.kartverket.nibas.flatbuffer.Nibas.Koordinat coordinates(no.kartverket.nibas.flatbuffer.Nibas.Koordinat obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o) + j * 8, bb) : null; }
  public int coordinatesLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public no.kartverket.nibas.flatbuffer.Nibas.Koordinat.Vector coordinatesVector() { return coordinatesVector(new no.kartverket.nibas.flatbuffer.Nibas.Koordinat.Vector()); }
  public no.kartverket.nibas.flatbuffer.Nibas.Koordinat.Vector coordinatesVector(no.kartverket.nibas.flatbuffer.Nibas.Koordinat.Vector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), 8, bb) : null; }

  public static int createLinearRing(FlatBufferBuilder builder,
      int coordinatesOffset) {
    builder.startTable(1);
    LinearRing.addCoordinates(builder, coordinatesOffset);
    return LinearRing.endLinearRing(builder);
  }

  public static void startLinearRing(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addCoordinates(FlatBufferBuilder builder, int coordinatesOffset) { builder.addOffset(0, coordinatesOffset, 0); }
  public static void startCoordinatesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(8, numElems, 4); }
  public static int endLinearRing(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public LinearRing get(int j) { return get(new LinearRing(), j); }
    public LinearRing get(LinearRing obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

