// automatically generated by the FlatBuffers compiler, do not modify

package no.kartverket.nibas.flatbuffer.Nibas;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class MatrikkelGrensepunkt extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_24_3_25(); }
  public static MatrikkelGrensepunkt getRootAsMatrikkelGrensepunkt(ByteBuffer _bb) { return getRootAsMatrikkelGrensepunkt(_bb, new MatrikkelGrensepunkt()); }
  public static MatrikkelGrensepunkt getRootAsMatrikkelGrensepunkt(ByteBuffer _bb, MatrikkelGrensepunkt obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public MatrikkelGrensepunkt __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public no.kartverket.nibas.flatbuffer.Nibas.Koordinat coordinate() { return coordinate(new no.kartverket.nibas.flatbuffer.Nibas.Koordinat()); }
  public no.kartverket.nibas.flatbuffer.Nibas.Koordinat coordinate(no.kartverket.nibas.flatbuffer.Nibas.Koordinat obj) { int o = __offset(4); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }
  public byte grensmerkodeKode() { int o = __offset(6); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public byte grensemerkeNedsattIKode() { int o = __offset(8); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public byte maalemetodeKode() { int o = __offset(10); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public int maalingsnoyaktighet() { int o = __offset(12); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public no.kartverket.nibas.flatbuffer.Nibas.Common.LocalDate datafangstdato() { return datafangstdato(new no.kartverket.nibas.flatbuffer.Nibas.Common.LocalDate()); }
  public no.kartverket.nibas.flatbuffer.Nibas.Common.LocalDate datafangstdato(no.kartverket.nibas.flatbuffer.Nibas.Common.LocalDate obj) { int o = __offset(14); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }
  public String grensepunktnr() { int o = __offset(16); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer grensepunktnrAsByteBuffer() { return __vector_as_bytebuffer(16, 1); }
  public ByteBuffer grensepunktnrInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 16, 1); }
  public no.kartverket.nibas.flatbuffer.Nibas.Common.Timestamp oppdateringsdato() { return oppdateringsdato(new no.kartverket.nibas.flatbuffer.Nibas.Common.Timestamp()); }
  public no.kartverket.nibas.flatbuffer.Nibas.Common.Timestamp oppdateringsdato(no.kartverket.nibas.flatbuffer.Nibas.Common.Timestamp obj) { int o = __offset(18); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }

  public static void startMatrikkelGrensepunkt(FlatBufferBuilder builder) { builder.startTable(8); }
  public static void addCoordinate(FlatBufferBuilder builder, int coordinateOffset) { builder.addStruct(0, coordinateOffset, 0); }
  public static void addGrensmerkodeKode(FlatBufferBuilder builder, byte grensmerkodeKode) { builder.addByte(1, grensmerkodeKode, 0); }
  public static void addGrensemerkeNedsattIKode(FlatBufferBuilder builder, byte grensemerkeNedsattIKode) { builder.addByte(2, grensemerkeNedsattIKode, 0); }
  public static void addMaalemetodeKode(FlatBufferBuilder builder, byte maalemetodeKode) { builder.addByte(3, maalemetodeKode, 0); }
  public static void addMaalingsnoyaktighet(FlatBufferBuilder builder, int maalingsnoyaktighet) { builder.addInt(4, maalingsnoyaktighet, 0); }
  public static void addDatafangstdato(FlatBufferBuilder builder, int datafangstdatoOffset) { builder.addStruct(5, datafangstdatoOffset, 0); }
  public static void addGrensepunktnr(FlatBufferBuilder builder, int grensepunktnrOffset) { builder.addOffset(6, grensepunktnrOffset, 0); }
  public static void addOppdateringsdato(FlatBufferBuilder builder, int oppdateringsdatoOffset) { builder.addStruct(7, oppdateringsdatoOffset, 0); }
  public static int endMatrikkelGrensepunkt(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public MatrikkelGrensepunkt get(int j) { return get(new MatrikkelGrensepunkt(), j); }
    public MatrikkelGrensepunkt get(MatrikkelGrensepunkt obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

