// automatically generated by the FlatBuffers compiler, do not modify

package no.kartverket.nibas.flatbuffer.Nibas;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class MatrikkelGrensepunktDB extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_24_3_25(); }
  public static MatrikkelGrensepunktDB getRootAsMatrikkelGrensepunktDB(ByteBuffer _bb) { return getRootAsMatrikkelGrensepunktDB(_bb, new MatrikkelGrensepunktDB()); }
  public static MatrikkelGrensepunktDB getRootAsMatrikkelGrensepunktDB(ByteBuffer _bb, MatrikkelGrensepunktDB obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public MatrikkelGrensepunktDB __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public no.kartverket.nibas.flatbuffer.Nibas.MatrikkelGrensepunktEntry matrikkelgrensepunkter(int j) { return matrikkelgrensepunkter(new no.kartverket.nibas.flatbuffer.Nibas.MatrikkelGrensepunktEntry(), j); }
  public no.kartverket.nibas.flatbuffer.Nibas.MatrikkelGrensepunktEntry matrikkelgrensepunkter(no.kartverket.nibas.flatbuffer.Nibas.MatrikkelGrensepunktEntry obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int matrikkelgrensepunkterLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public no.kartverket.nibas.flatbuffer.Nibas.MatrikkelGrensepunktEntry matrikkelgrensepunkterByKey(long key) { int o = __offset(4); return o != 0 ? no.kartverket.nibas.flatbuffer.Nibas.MatrikkelGrensepunktEntry.__lookup_by_key(null, __vector(o), key, bb) : null; }
  public no.kartverket.nibas.flatbuffer.Nibas.MatrikkelGrensepunktEntry matrikkelgrensepunkterByKey(no.kartverket.nibas.flatbuffer.Nibas.MatrikkelGrensepunktEntry obj, long key) { int o = __offset(4); return o != 0 ? no.kartverket.nibas.flatbuffer.Nibas.MatrikkelGrensepunktEntry.__lookup_by_key(obj, __vector(o), key, bb) : null; }
  public no.kartverket.nibas.flatbuffer.Nibas.MatrikkelGrensepunktEntry.Vector matrikkelgrensepunkterVector() { return matrikkelgrensepunkterVector(new no.kartverket.nibas.flatbuffer.Nibas.MatrikkelGrensepunktEntry.Vector()); }
  public no.kartverket.nibas.flatbuffer.Nibas.MatrikkelGrensepunktEntry.Vector matrikkelgrensepunkterVector(no.kartverket.nibas.flatbuffer.Nibas.MatrikkelGrensepunktEntry.Vector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public long firstKey() { int o = __offset(6); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public long lastKey() { int o = __offset(8); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }

  public static int createMatrikkelGrensepunktDB(FlatBufferBuilder builder,
      int matrikkelgrensepunkterOffset,
      long firstKey,
      long lastKey) {
    builder.startTable(3);
    MatrikkelGrensepunktDB.addLastKey(builder, lastKey);
    MatrikkelGrensepunktDB.addFirstKey(builder, firstKey);
    MatrikkelGrensepunktDB.addMatrikkelgrensepunkter(builder, matrikkelgrensepunkterOffset);
    return MatrikkelGrensepunktDB.endMatrikkelGrensepunktDB(builder);
  }

  public static void startMatrikkelGrensepunktDB(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addMatrikkelgrensepunkter(FlatBufferBuilder builder, int matrikkelgrensepunkterOffset) { builder.addOffset(0, matrikkelgrensepunkterOffset, 0); }
  public static int createMatrikkelgrensepunkterVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startMatrikkelgrensepunkterVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addFirstKey(FlatBufferBuilder builder, long firstKey) { builder.addLong(1, firstKey, 0L); }
  public static void addLastKey(FlatBufferBuilder builder, long lastKey) { builder.addLong(2, lastKey, 0L); }
  public static int endMatrikkelGrensepunktDB(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 4);  // matrikkelgrensepunkter
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public MatrikkelGrensepunktDB get(int j) { return get(new MatrikkelGrensepunktDB(), j); }
    public MatrikkelGrensepunktDB get(MatrikkelGrensepunktDB obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

