// automatically generated by the FlatBuffers compiler, do not modify

package no.kartverket.nibas.flatbuffer.Nibas;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class MatrikkelGrensepunktEntry extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_24_3_25(); }
  public static MatrikkelGrensepunktEntry getRootAsMatrikkelGrensepunktEntry(ByteBuffer _bb) { return getRootAsMatrikkelGrensepunktEntry(_bb, new MatrikkelGrensepunktEntry()); }
  public static MatrikkelGrensepunktEntry getRootAsMatrikkelGrensepunktEntry(ByteBuffer _bb, MatrikkelGrensepunktEntry obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public MatrikkelGrensepunktEntry __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long id() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public no.kartverket.nibas.flatbuffer.Nibas.MatrikkelGrensepunkt grensepunkt() { return grensepunkt(new no.kartverket.nibas.flatbuffer.Nibas.MatrikkelGrensepunkt()); }
  public no.kartverket.nibas.flatbuffer.Nibas.MatrikkelGrensepunkt grensepunkt(no.kartverket.nibas.flatbuffer.Nibas.MatrikkelGrensepunkt obj) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }

  public static int createMatrikkelGrensepunktEntry(FlatBufferBuilder builder,
      long id,
      int grensepunktOffset) {
    builder.startTable(2);
    MatrikkelGrensepunktEntry.addId(builder, id);
    MatrikkelGrensepunktEntry.addGrensepunkt(builder, grensepunktOffset);
    return MatrikkelGrensepunktEntry.endMatrikkelGrensepunktEntry(builder);
  }

  public static void startMatrikkelGrensepunktEntry(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addId(FlatBufferBuilder builder, long id) { builder.addLong(id); builder.slot(0); }
  public static void addGrensepunkt(FlatBufferBuilder builder, int grensepunktOffset) { builder.addOffset(1, grensepunktOffset, 0); }
  public static int endMatrikkelGrensepunktEntry(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 6);  // grensepunkt
    return o;
  }

  @Override
  protected int keysCompare(Integer o1, Integer o2, ByteBuffer _bb) {
    long val_1 = _bb.getLong(__offset(4, o1, _bb));
    long val_2 = _bb.getLong(__offset(4, o2, _bb));
    return val_1 > val_2 ? 1 : val_1 < val_2 ? -1 : 0;
  }

  public static MatrikkelGrensepunktEntry __lookup_by_key(MatrikkelGrensepunktEntry obj, int vectorLocation, long key, ByteBuffer bb) {
    int span = bb.getInt(vectorLocation - 4);
    int start = 0;
    while (span != 0) {
      int middle = span / 2;
      int tableOffset = __indirect(vectorLocation + 4 * (start + middle), bb);
      long val = bb.getLong(__offset(4, bb.capacity() - tableOffset, bb));
      int comp = val > key ? 1 : val < key ? -1 : 0;
      if (comp > 0) {
        span = middle;
      } else if (comp < 0) {
        middle++;
        start += middle;
        span -= middle;
      } else {
        return (obj == null ? new MatrikkelGrensepunktEntry() : obj).__assign(tableOffset, bb);
      }
    }
    return null;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public MatrikkelGrensepunktEntry get(int j) { return get(new MatrikkelGrensepunktEntry(), j); }
    public MatrikkelGrensepunktEntry get(MatrikkelGrensepunktEntry obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
    public MatrikkelGrensepunktEntry getByKey(long key) {  return __lookup_by_key(null, __vector(), key, bb); }
    public MatrikkelGrensepunktEntry getByKey(MatrikkelGrensepunktEntry obj, long key) {  return __lookup_by_key(obj, __vector(), key, bb); }
  }
}

