// automatically generated by the FlatBuffers compiler, do not modify

package no.kartverket.nibas.flatbuffer.MatrikkelDB;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class GrenselinjeDirection extends Struct {
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public GrenselinjeDirection __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long grenselinjeId() { return bb.getLong(bb_pos + 0); }
  public boolean reversed() { return 0!=bb.get(bb_pos + 8); }

  public static int createGrenselinjeDirection(FlatBufferBuilder builder, long grenselinjeId, boolean reversed) {
    builder.prep(8, 16);
    builder.pad(7);
    builder.putBoolean(reversed);
    builder.putLong(grenselinjeId);
    return builder.offset();
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public GrenselinjeDirection get(int j) { return get(new GrenselinjeDirection(), j); }
    public GrenselinjeDirection get(GrenselinjeDirection obj, int j) {  return obj.__assign(__element(j), bb); }
  }
}

