// automatically generated by the FlatBuffers compiler, do not modify

package no.kartverket.nibas.flatbuffer.MatrikkelDB;

@SuppressWarnings("unused")
public final class LineGeometry {
  private LineGeometry() { }
  public static final byte NONE = 0;
  public static final byte Polyline = 1;
  public static final byte Arc = 2;

  public static final String[] names = { "NONE", "Polyline", "Arc", };

  public static String name(int e) { return names[e]; }
}

