// automatically generated by the FlatBuffers compiler, do not modify

package no.kartverket.nibas.flatbuffer.MatrikkelDB;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Posisjonskvalitet extends Struct {
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Posisjonskvalitet __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte maalemetodeKode() { return bb.get(bb_pos + 0); }
  public int noyaktighet() { return bb.getInt(bb_pos + 4); }

  public static int createPosisjonskvalitet(FlatBufferBuilder builder, byte maalemetodeKode, int noyaktighet) {
    builder.prep(4, 8);
    builder.putInt(noyaktighet);
    builder.pad(3);
    builder.putByte(maalemetodeKode);
    return builder.offset();
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Posisjonskvalitet get(int j) { return get(new Posisjonskvalitet(), j); }
    public Posisjonskvalitet get(Posisjonskvalitet obj, int j) {  return obj.__assign(__element(j), bb); }
  }
}

