// automatically generated by the FlatBuffers compiler, do not modify

package no.kartverket.nibas.flatbuffer.MatrikkelDB;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class GrensepunktBuffer extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static GrensepunktBuffer getRootAsGrensepunktBuffer(ByteBuffer _bb) { return getRootAsGrensepunktBuffer(_bb, new GrensepunktBuffer()); }
  public static GrensepunktBuffer getRootAsGrensepunktBuffer(ByteBuffer _bb, GrensepunktBuffer obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public GrensepunktBuffer __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public no.kartverket.nibas.flatbuffer.MatrikkelDB.Grensepunkt grensepunkter(int j) { return grensepunkter(new no.kartverket.nibas.flatbuffer.MatrikkelDB.Grensepunkt(), j); }
  public no.kartverket.nibas.flatbuffer.MatrikkelDB.Grensepunkt grensepunkter(no.kartverket.nibas.flatbuffer.MatrikkelDB.Grensepunkt obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int grensepunkterLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public no.kartverket.nibas.flatbuffer.MatrikkelDB.Grensepunkt.Vector grensepunkterVector() { return grensepunkterVector(new no.kartverket.nibas.flatbuffer.MatrikkelDB.Grensepunkt.Vector()); }
  public no.kartverket.nibas.flatbuffer.MatrikkelDB.Grensepunkt.Vector grensepunkterVector(no.kartverket.nibas.flatbuffer.MatrikkelDB.Grensepunkt.Vector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public long koordinatScale() { int o = __offset(6); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }

  public static int createGrensepunktBuffer(FlatBufferBuilder builder,
      int grensepunkterOffset,
      long koordinatScale) {
    builder.startTable(2);
    GrensepunktBuffer.addKoordinatScale(builder, koordinatScale);
    GrensepunktBuffer.addGrensepunkter(builder, grensepunkterOffset);
    return GrensepunktBuffer.endGrensepunktBuffer(builder);
  }

  public static void startGrensepunktBuffer(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addGrensepunkter(FlatBufferBuilder builder, int grensepunkterOffset) { builder.addOffset(0, grensepunkterOffset, 0); }
  public static int createGrensepunkterVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startGrensepunkterVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addKoordinatScale(FlatBufferBuilder builder, long koordinatScale) { builder.addInt(1, (int) koordinatScale, (int) 0L); }
  public static int endGrensepunktBuffer(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public GrensepunktBuffer get(int j) { return get(new GrensepunktBuffer(), j); }
    public GrensepunktBuffer get(GrensepunktBuffer obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

