// automatically generated by the FlatBuffers compiler, do not modify

package no.kartverket.nibas.flatbuffer.MatrikkelDB;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class GrenselinjeBuffer extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_24_3_25(); }
  public static GrenselinjeBuffer getRootAsGrenselinjeBuffer(ByteBuffer _bb) { return getRootAsGrenselinjeBuffer(_bb, new GrenselinjeBuffer()); }
  public static GrenselinjeBuffer getRootAsGrenselinjeBuffer(ByteBuffer _bb, GrenselinjeBuffer obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public GrenselinjeBuffer __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public no.kartverket.nibas.flatbuffer.MatrikkelDB.Grenselinje grenselinjer(int j) { return grenselinjer(new no.kartverket.nibas.flatbuffer.MatrikkelDB.Grenselinje(), j); }
  public no.kartverket.nibas.flatbuffer.MatrikkelDB.Grenselinje grenselinjer(no.kartverket.nibas.flatbuffer.MatrikkelDB.Grenselinje obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int grenselinjerLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public no.kartverket.nibas.flatbuffer.MatrikkelDB.Grenselinje.Vector grenselinjerVector() { return grenselinjerVector(new no.kartverket.nibas.flatbuffer.MatrikkelDB.Grenselinje.Vector()); }
  public no.kartverket.nibas.flatbuffer.MatrikkelDB.Grenselinje.Vector grenselinjerVector(no.kartverket.nibas.flatbuffer.MatrikkelDB.Grenselinje.Vector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public long koordinatScale() { int o = __offset(6); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }

  public static int createGrenselinjeBuffer(FlatBufferBuilder builder,
      int grenselinjerOffset,
      long koordinatScale) {
    builder.startTable(2);
    GrenselinjeBuffer.addKoordinatScale(builder, koordinatScale);
    GrenselinjeBuffer.addGrenselinjer(builder, grenselinjerOffset);
    return GrenselinjeBuffer.endGrenselinjeBuffer(builder);
  }

  public static void startGrenselinjeBuffer(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addGrenselinjer(FlatBufferBuilder builder, int grenselinjerOffset) { builder.addOffset(0, grenselinjerOffset, 0); }
  public static int createGrenselinjerVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startGrenselinjerVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addKoordinatScale(FlatBufferBuilder builder, long koordinatScale) { builder.addInt(1, (int) koordinatScale, (int) 0L); }
  public static int endGrenselinjeBuffer(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public GrenselinjeBuffer get(int j) { return get(new GrenselinjeBuffer(), j); }
    public GrenselinjeBuffer get(GrenselinjeBuffer obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

