// automatically generated by the FlatBuffers compiler, do not modify

package no.kartverket.nibas.flatbuffer.MatrikkelDB;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Grenselinje extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static Grenselinje getRootAsGrenselinje(ByteBuffer _bb) { return getRootAsGrenselinje(_bb, new Grenselinje()); }
  public static Grenselinje getRootAsGrenselinje(ByteBuffer _bb, Grenselinje obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Grenselinje __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long id() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public byte hjelpelinjeKode() { int o = __offset(6); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public boolean omtvistet() { int o = __offset(8); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public byte terrengdetaljKode() { int o = __offset(10); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public byte administrativGrenseKode() { int o = __offset(12); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public no.kartverket.nibas.flatbuffer.MatrikkelDB.Posisjonskvalitet posisjonskvalitet() { return posisjonskvalitet(new no.kartverket.nibas.flatbuffer.MatrikkelDB.Posisjonskvalitet()); }
  public no.kartverket.nibas.flatbuffer.MatrikkelDB.Posisjonskvalitet posisjonskvalitet(no.kartverket.nibas.flatbuffer.MatrikkelDB.Posisjonskvalitet obj) { int o = __offset(14); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }
  public no.kartverket.nibas.flatbuffer.Nibas.Common.LocalDate datafangstdato() { return datafangstdato(new no.kartverket.nibas.flatbuffer.Nibas.Common.LocalDate()); }
  public no.kartverket.nibas.flatbuffer.Nibas.Common.LocalDate datafangstdato(no.kartverket.nibas.flatbuffer.Nibas.Common.LocalDate obj) { int o = __offset(16); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }
  public byte noyaktighetsklasse() { int o = __offset(18); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public byte lineGeometryType() { int o = __offset(20); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public Table lineGeometry(Table obj) { int o = __offset(22); return o != 0 ? __union(obj, o + bb_pos) : null; }
  public no.kartverket.nibas.flatbuffer.Nibas.Common.Timestamp oppdateringsdato() { return oppdateringsdato(new no.kartverket.nibas.flatbuffer.Nibas.Common.Timestamp()); }
  public no.kartverket.nibas.flatbuffer.Nibas.Common.Timestamp oppdateringsdato(no.kartverket.nibas.flatbuffer.Nibas.Common.Timestamp obj) { int o = __offset(24); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }
  public String kommunenrstrengcache() { int o = __offset(26); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer kommunenrstrengcacheAsByteBuffer() { return __vector_as_bytebuffer(26, 1); }
  public ByteBuffer kommunenrstrengcacheInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 26, 1); }
  public String informasjon() { int o = __offset(28); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer informasjonAsByteBuffer() { return __vector_as_bytebuffer(28, 1); }
  public ByteBuffer informasjonInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 28, 1); }
  public int versjon() { int o = __offset(30); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int versjonid() { int o = __offset(32); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public String oppdatertav() { int o = __offset(34); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer oppdatertavAsByteBuffer() { return __vector_as_bytebuffer(34, 1); }
  public ByteBuffer oppdatertavInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 34, 1); }

  public static void startGrenselinje(FlatBufferBuilder builder) { builder.startTable(16); }
  public static void addId(FlatBufferBuilder builder, long id) { builder.addLong(0, id, 0L); }
  public static void addHjelpelinjeKode(FlatBufferBuilder builder, byte hjelpelinjeKode) { builder.addByte(1, hjelpelinjeKode, 0); }
  public static void addOmtvistet(FlatBufferBuilder builder, boolean omtvistet) { builder.addBoolean(2, omtvistet, false); }
  public static void addTerrengdetaljKode(FlatBufferBuilder builder, byte terrengdetaljKode) { builder.addByte(3, terrengdetaljKode, 0); }
  public static void addAdministrativGrenseKode(FlatBufferBuilder builder, byte administrativGrenseKode) { builder.addByte(4, administrativGrenseKode, 0); }
  public static void addPosisjonskvalitet(FlatBufferBuilder builder, int posisjonskvalitetOffset) { builder.addStruct(5, posisjonskvalitetOffset, 0); }
  public static void addDatafangstdato(FlatBufferBuilder builder, int datafangstdatoOffset) { builder.addStruct(6, datafangstdatoOffset, 0); }
  public static void addNoyaktighetsklasse(FlatBufferBuilder builder, byte noyaktighetsklasse) { builder.addByte(7, noyaktighetsklasse, 0); }
  public static void addLineGeometryType(FlatBufferBuilder builder, byte lineGeometryType) { builder.addByte(8, lineGeometryType, 0); }
  public static void addLineGeometry(FlatBufferBuilder builder, int lineGeometryOffset) { builder.addOffset(9, lineGeometryOffset, 0); }
  public static void addOppdateringsdato(FlatBufferBuilder builder, int oppdateringsdatoOffset) { builder.addStruct(10, oppdateringsdatoOffset, 0); }
  public static void addKommunenrstrengcache(FlatBufferBuilder builder, int kommunenrstrengcacheOffset) { builder.addOffset(11, kommunenrstrengcacheOffset, 0); }
  public static void addInformasjon(FlatBufferBuilder builder, int informasjonOffset) { builder.addOffset(12, informasjonOffset, 0); }
  public static void addVersjon(FlatBufferBuilder builder, int versjon) { builder.addInt(13, versjon, 0); }
  public static void addVersjonid(FlatBufferBuilder builder, int versjonid) { builder.addInt(14, versjonid, 0); }
  public static void addOppdatertav(FlatBufferBuilder builder, int oppdatertavOffset) { builder.addOffset(15, oppdatertavOffset, 0); }
  public static int endGrenselinje(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Grenselinje get(int j) { return get(new Grenselinje(), j); }
    public Grenselinje get(Grenselinje obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

