// automatically generated by the FlatBuffers compiler, do not modify

package no.kartverket.nibas.flatbuffer.MatrikkelDB;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Grensepunkt extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static Grensepunkt getRootAsGrensepunkt(ByteBuffer _bb) { return getRootAsGrensepunkt(_bb, new Grensepunkt()); }
  public static Grensepunkt getRootAsGrensepunkt(ByteBuffer _bb, Grensepunkt obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Grensepunkt __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long id() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public no.kartverket.nibas.flatbuffer.MatrikkelDB.Koordinat koordinat() { return koordinat(new no.kartverket.nibas.flatbuffer.MatrikkelDB.Koordinat()); }
  public no.kartverket.nibas.flatbuffer.MatrikkelDB.Koordinat koordinat(no.kartverket.nibas.flatbuffer.MatrikkelDB.Koordinat obj) { int o = __offset(6); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }
  public byte koordinatsystemKode() { int o = __offset(8); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public byte grensmerkodeKode() { int o = __offset(10); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public byte grensemerkeNedsattIKode() { int o = __offset(12); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public no.kartverket.nibas.flatbuffer.MatrikkelDB.Posisjonskvalitet posisjonskvalitet() { return posisjonskvalitet(new no.kartverket.nibas.flatbuffer.MatrikkelDB.Posisjonskvalitet()); }
  public no.kartverket.nibas.flatbuffer.MatrikkelDB.Posisjonskvalitet posisjonskvalitet(no.kartverket.nibas.flatbuffer.MatrikkelDB.Posisjonskvalitet obj) { int o = __offset(14); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }
  public no.kartverket.nibas.flatbuffer.Nibas.Common.LocalDate datafangstdato() { return datafangstdato(new no.kartverket.nibas.flatbuffer.Nibas.Common.LocalDate()); }
  public no.kartverket.nibas.flatbuffer.Nibas.Common.LocalDate datafangstdato(no.kartverket.nibas.flatbuffer.Nibas.Common.LocalDate obj) { int o = __offset(16); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }
  public String grensepunktnr() { int o = __offset(18); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer grensepunktnrAsByteBuffer() { return __vector_as_bytebuffer(18, 1); }
  public ByteBuffer grensepunktnrInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 18, 1); }
  public no.kartverket.nibas.flatbuffer.Nibas.Common.Timestamp oppdateringsdato() { return oppdateringsdato(new no.kartverket.nibas.flatbuffer.Nibas.Common.Timestamp()); }
  public no.kartverket.nibas.flatbuffer.Nibas.Common.Timestamp oppdateringsdato(no.kartverket.nibas.flatbuffer.Nibas.Common.Timestamp obj) { int o = __offset(20); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }

  public static void startGrensepunkt(FlatBufferBuilder builder) { builder.startTable(9); }
  public static void addId(FlatBufferBuilder builder, long id) { builder.addLong(0, id, 0L); }
  public static void addKoordinat(FlatBufferBuilder builder, int koordinatOffset) { builder.addStruct(1, koordinatOffset, 0); }
  public static void addKoordinatsystemKode(FlatBufferBuilder builder, byte koordinatsystemKode) { builder.addByte(2, koordinatsystemKode, 0); }
  public static void addGrensmerkodeKode(FlatBufferBuilder builder, byte grensmerkodeKode) { builder.addByte(3, grensmerkodeKode, 0); }
  public static void addGrensemerkeNedsattIKode(FlatBufferBuilder builder, byte grensemerkeNedsattIKode) { builder.addByte(4, grensemerkeNedsattIKode, 0); }
  public static void addPosisjonskvalitet(FlatBufferBuilder builder, int posisjonskvalitetOffset) { builder.addStruct(5, posisjonskvalitetOffset, 0); }
  public static void addDatafangstdato(FlatBufferBuilder builder, int datafangstdatoOffset) { builder.addStruct(6, datafangstdatoOffset, 0); }
  public static void addGrensepunktnr(FlatBufferBuilder builder, int grensepunktnrOffset) { builder.addOffset(7, grensepunktnrOffset, 0); }
  public static void addOppdateringsdato(FlatBufferBuilder builder, int oppdateringsdatoOffset) { builder.addStruct(8, oppdateringsdatoOffset, 0); }
  public static int endGrensepunkt(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Grensepunkt get(int j) { return get(new Grensepunkt(), j); }
    public Grensepunkt get(Grensepunkt obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

