// automatically generated by the FlatBuffers compiler, do not modify

package no.kartverket.nibas.flatbuffer.MatrikkelDB;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Polyline extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_24_3_25(); }
  public static Polyline getRootAsPolyline(ByteBuffer _bb) { return getRootAsPolyline(_bb, new Polyline()); }
  public static Polyline getRootAsPolyline(ByteBuffer _bb, Polyline obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Polyline __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long firstPointId() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public no.kartverket.nibas.flatbuffer.MatrikkelDB.Koordinat middlePointCoordinates(int j) { return middlePointCoordinates(new no.kartverket.nibas.flatbuffer.MatrikkelDB.Koordinat(), j); }
  public no.kartverket.nibas.flatbuffer.MatrikkelDB.Koordinat middlePointCoordinates(no.kartverket.nibas.flatbuffer.MatrikkelDB.Koordinat obj, int j) { int o = __offset(6); return o != 0 ? obj.__assign(__vector(o) + j * 16, bb) : null; }
  public int middlePointCoordinatesLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public no.kartverket.nibas.flatbuffer.MatrikkelDB.Koordinat.Vector middlePointCoordinatesVector() { return middlePointCoordinatesVector(new no.kartverket.nibas.flatbuffer.MatrikkelDB.Koordinat.Vector()); }
  public no.kartverket.nibas.flatbuffer.MatrikkelDB.Koordinat.Vector middlePointCoordinatesVector(no.kartverket.nibas.flatbuffer.MatrikkelDB.Koordinat.Vector obj) { int o = __offset(6); return o != 0 ? obj.__assign(__vector(o), 16, bb) : null; }
  public long lastPointId() { int o = __offset(8); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public byte koordinatsystemKode() { int o = __offset(10); return o != 0 ? bb.get(o + bb_pos) : 0; }

  public static int createPolyline(FlatBufferBuilder builder,
      long firstPointId,
      int middlePointCoordinatesOffset,
      long lastPointId,
      byte koordinatsystemKode) {
    builder.startTable(4);
    Polyline.addLastPointId(builder, lastPointId);
    Polyline.addFirstPointId(builder, firstPointId);
    Polyline.addMiddlePointCoordinates(builder, middlePointCoordinatesOffset);
    Polyline.addKoordinatsystemKode(builder, koordinatsystemKode);
    return Polyline.endPolyline(builder);
  }

  public static void startPolyline(FlatBufferBuilder builder) { builder.startTable(4); }
  public static void addFirstPointId(FlatBufferBuilder builder, long firstPointId) { builder.addLong(0, firstPointId, 0L); }
  public static void addMiddlePointCoordinates(FlatBufferBuilder builder, int middlePointCoordinatesOffset) { builder.addOffset(1, middlePointCoordinatesOffset, 0); }
  public static void startMiddlePointCoordinatesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(16, numElems, 8); }
  public static void addLastPointId(FlatBufferBuilder builder, long lastPointId) { builder.addLong(2, lastPointId, 0L); }
  public static void addKoordinatsystemKode(FlatBufferBuilder builder, byte koordinatsystemKode) { builder.addByte(3, koordinatsystemKode, 0); }
  public static int endPolyline(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Polyline get(int j) { return get(new Polyline(), j); }
    public Polyline get(Polyline obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

