// automatically generated by the FlatBuffers compiler, do not modify

package no.kartverket.nibas.flatbuffer.MatrikkelDB;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class TeigInterior extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static TeigInterior getRootAsTeigInterior(ByteBuffer _bb) { return getRootAsTeigInterior(_bb, new TeigInterior()); }
  public static TeigInterior getRootAsTeigInterior(ByteBuffer _bb, TeigInterior obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public TeigInterior __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public no.kartverket.nibas.flatbuffer.MatrikkelDB.GrenselinjeDirection grenselinjeDirections(int j) { return grenselinjeDirections(new no.kartverket.nibas.flatbuffer.MatrikkelDB.GrenselinjeDirection(), j); }
  public no.kartverket.nibas.flatbuffer.MatrikkelDB.GrenselinjeDirection grenselinjeDirections(no.kartverket.nibas.flatbuffer.MatrikkelDB.GrenselinjeDirection obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o) + j * 16, bb) : null; }
  public int grenselinjeDirectionsLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public no.kartverket.nibas.flatbuffer.MatrikkelDB.GrenselinjeDirection.Vector grenselinjeDirectionsVector() { return grenselinjeDirectionsVector(new no.kartverket.nibas.flatbuffer.MatrikkelDB.GrenselinjeDirection.Vector()); }
  public no.kartverket.nibas.flatbuffer.MatrikkelDB.GrenselinjeDirection.Vector grenselinjeDirectionsVector(no.kartverket.nibas.flatbuffer.MatrikkelDB.GrenselinjeDirection.Vector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), 16, bb) : null; }

  public static int createTeigInterior(FlatBufferBuilder builder,
      int grenselinjeDirectionsOffset) {
    builder.startTable(1);
    TeigInterior.addGrenselinjeDirections(builder, grenselinjeDirectionsOffset);
    return TeigInterior.endTeigInterior(builder);
  }

  public static void startTeigInterior(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addGrenselinjeDirections(FlatBufferBuilder builder, int grenselinjeDirectionsOffset) { builder.addOffset(0, grenselinjeDirectionsOffset, 0); }
  public static void startGrenselinjeDirectionsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(16, numElems, 8); }
  public static int endTeigInterior(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public TeigInterior get(int j) { return get(new TeigInterior(), j); }
    public TeigInterior get(TeigInterior obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

