// automatically generated by the FlatBuffers compiler, do not modify

package no.kartverket.nibas.flatbuffer.MatrikkelDB;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class TeigBuffer extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_24_3_25(); }
  public static TeigBuffer getRootAsTeigBuffer(ByteBuffer _bb) { return getRootAsTeigBuffer(_bb, new TeigBuffer()); }
  public static TeigBuffer getRootAsTeigBuffer(ByteBuffer _bb, TeigBuffer obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public TeigBuffer __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public no.kartverket.nibas.flatbuffer.MatrikkelDB.Teig teiger(int j) { return teiger(new no.kartverket.nibas.flatbuffer.MatrikkelDB.Teig(), j); }
  public no.kartverket.nibas.flatbuffer.MatrikkelDB.Teig teiger(no.kartverket.nibas.flatbuffer.MatrikkelDB.Teig obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int teigerLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public no.kartverket.nibas.flatbuffer.MatrikkelDB.Teig.Vector teigerVector() { return teigerVector(new no.kartverket.nibas.flatbuffer.MatrikkelDB.Teig.Vector()); }
  public no.kartverket.nibas.flatbuffer.MatrikkelDB.Teig.Vector teigerVector(no.kartverket.nibas.flatbuffer.MatrikkelDB.Teig.Vector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createTeigBuffer(FlatBufferBuilder builder,
      int teigerOffset) {
    builder.startTable(1);
    TeigBuffer.addTeiger(builder, teigerOffset);
    return TeigBuffer.endTeigBuffer(builder);
  }

  public static void startTeigBuffer(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addTeiger(FlatBufferBuilder builder, int teigerOffset) { builder.addOffset(0, teigerOffset, 0); }
  public static int createTeigerVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startTeigerVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endTeigBuffer(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public TeigBuffer get(int j) { return get(new TeigBuffer(), j); }
    public TeigBuffer get(TeigBuffer obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

