// automatically generated by the FlatBuffers compiler, do not modify

package no.kartverket.nibas.flatbuffer.MatrikkelDB;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Teig extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_24_3_25(); }
  public static Teig getRootAsTeig(ByteBuffer _bb) { return getRootAsTeig(_bb, new Teig()); }
  public static Teig getRootAsTeig(ByteBuffer _bb, Teig obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Teig __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long teigId() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public no.kartverket.nibas.flatbuffer.Nibas.Common.Matrikkelnummer matrikkelnummer(int j) { return matrikkelnummer(new no.kartverket.nibas.flatbuffer.Nibas.Common.Matrikkelnummer(), j); }
  public no.kartverket.nibas.flatbuffer.Nibas.Common.Matrikkelnummer matrikkelnummer(no.kartverket.nibas.flatbuffer.Nibas.Common.Matrikkelnummer obj, int j) { int o = __offset(6); return o != 0 ? obj.__assign(__vector(o) + j * 16, bb) : null; }
  public int matrikkelnummerLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public no.kartverket.nibas.flatbuffer.Nibas.Common.Matrikkelnummer.Vector matrikkelnummerVector() { return matrikkelnummerVector(new no.kartverket.nibas.flatbuffer.Nibas.Common.Matrikkelnummer.Vector()); }
  public no.kartverket.nibas.flatbuffer.Nibas.Common.Matrikkelnummer.Vector matrikkelnummerVector(no.kartverket.nibas.flatbuffer.Nibas.Common.Matrikkelnummer.Vector obj) { int o = __offset(6); return o != 0 ? obj.__assign(__vector(o), 16, bb) : null; }
  public no.kartverket.nibas.flatbuffer.MatrikkelDB.GrenselinjeDirection grenselinjeDirections(int j) { return grenselinjeDirections(new no.kartverket.nibas.flatbuffer.MatrikkelDB.GrenselinjeDirection(), j); }
  public no.kartverket.nibas.flatbuffer.MatrikkelDB.GrenselinjeDirection grenselinjeDirections(no.kartverket.nibas.flatbuffer.MatrikkelDB.GrenselinjeDirection obj, int j) { int o = __offset(8); return o != 0 ? obj.__assign(__vector(o) + j * 16, bb) : null; }
  public int grenselinjeDirectionsLength() { int o = __offset(8); return o != 0 ? __vector_len(o) : 0; }
  public no.kartverket.nibas.flatbuffer.MatrikkelDB.GrenselinjeDirection.Vector grenselinjeDirectionsVector() { return grenselinjeDirectionsVector(new no.kartverket.nibas.flatbuffer.MatrikkelDB.GrenselinjeDirection.Vector()); }
  public no.kartverket.nibas.flatbuffer.MatrikkelDB.GrenselinjeDirection.Vector grenselinjeDirectionsVector(no.kartverket.nibas.flatbuffer.MatrikkelDB.GrenselinjeDirection.Vector obj) { int o = __offset(8); return o != 0 ? obj.__assign(__vector(o), 16, bb) : null; }
  public no.kartverket.nibas.flatbuffer.MatrikkelDB.TeigInterior interiors(int j) { return interiors(new no.kartverket.nibas.flatbuffer.MatrikkelDB.TeigInterior(), j); }
  public no.kartverket.nibas.flatbuffer.MatrikkelDB.TeigInterior interiors(no.kartverket.nibas.flatbuffer.MatrikkelDB.TeigInterior obj, int j) { int o = __offset(10); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int interiorsLength() { int o = __offset(10); return o != 0 ? __vector_len(o) : 0; }
  public no.kartverket.nibas.flatbuffer.MatrikkelDB.TeigInterior.Vector interiorsVector() { return interiorsVector(new no.kartverket.nibas.flatbuffer.MatrikkelDB.TeigInterior.Vector()); }
  public no.kartverket.nibas.flatbuffer.MatrikkelDB.TeigInterior.Vector interiorsVector(no.kartverket.nibas.flatbuffer.MatrikkelDB.TeigInterior.Vector obj) { int o = __offset(10); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createTeig(FlatBufferBuilder builder,
      long teigId,
      int matrikkelnummerOffset,
      int grenselinjeDirectionsOffset,
      int interiorsOffset) {
    builder.startTable(4);
    Teig.addTeigId(builder, teigId);
    Teig.addInteriors(builder, interiorsOffset);
    Teig.addGrenselinjeDirections(builder, grenselinjeDirectionsOffset);
    Teig.addMatrikkelnummer(builder, matrikkelnummerOffset);
    return Teig.endTeig(builder);
  }

  public static void startTeig(FlatBufferBuilder builder) { builder.startTable(4); }
  public static void addTeigId(FlatBufferBuilder builder, long teigId) { builder.addLong(0, teigId, 0L); }
  public static void addMatrikkelnummer(FlatBufferBuilder builder, int matrikkelnummerOffset) { builder.addOffset(1, matrikkelnummerOffset, 0); }
  public static void startMatrikkelnummerVector(FlatBufferBuilder builder, int numElems) { builder.startVector(16, numElems, 4); }
  public static void addGrenselinjeDirections(FlatBufferBuilder builder, int grenselinjeDirectionsOffset) { builder.addOffset(2, grenselinjeDirectionsOffset, 0); }
  public static void startGrenselinjeDirectionsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(16, numElems, 8); }
  public static void addInteriors(FlatBufferBuilder builder, int interiorsOffset) { builder.addOffset(3, interiorsOffset, 0); }
  public static int createInteriorsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startInteriorsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endTeig(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Teig get(int j) { return get(new Teig(), j); }
    public Teig get(Teig obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

