name: 'Dependency Review and Graph'
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  contents: write
  pull-requests: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7

      - name: 'Setup Java'
        uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 #v6
        with:
          distribution: temurin
          java-version: 21

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@9c971963bec38e04b3d30dcc455b5382be2fdbfb #v6.3.0

      - name: 'Dependency Review'
        uses: actions/dependency-review-action@a1d282b36b6f3519aa1f3fc636f609c47dddb294 #v5.0.0
        if: github.event_name == 'pull_request'
        with:
          comment-summary-in-pr: always
          fail-on-severity: high
          fail-on-scopes: runtime
          deny-licenses: GPL-2.0, GPL-3.0, AGPL-3.0, GPL-2.0-only, GPL-3.0-only, AGPL-3.0-only, SSPL-1.0
          allow-dependencies-licenses: pkg:maven/org.eclipse.angus/angus-mail@2.0.3
