name: Dependabot Auto-merge
on: pull_request_target

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Octo STS
        uses: octo-sts/action@v1.0.0
        id: octo-sts
        with:
          scope: kartverket/nibas-arbeidsliste
          identity: nibas-arbeidsliste

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ steps.octo-sts.outputs.token }}

      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{ steps.octo-sts.outputs.token }}
